services:
  postgres:
    container_name: node_postgres
    build: ./db
    ports: 
      - 10000:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: usuariodb
    volumes:
      - nodepg_data:/var/lib/postgresql/data
    networks:
      - rede_node

  node-api-1:
    container_name: node_api_1
    build: .
    ports: 
      - 10001:3000
    networks:
      - rede_node
    depends_on:
      - postgres

  node-api-2:
    container_name: node_api_2
    build: .
    ports: 
      - 10002:3000
    networks:
      - rede_node
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    networks:
      - rede_node
    depends_on:
      - node-api-1
      - node-api-2

volumes:
  nodepg_data:

networks:
  rede_node:
    driver: bridge