services:
  postgres:
    container_name: node_postgres
    build: ./db
    ports: 
      - 10000:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: usuariodb
    volumes:
      - nodepg_data:/var/lib/postgresql/data
    networks:
      - rede_node

  node-api:
    container_name: node_api
    build: .
    ports: 
      - 10001:3000
    networks:
      - rede_node
    depends_on:
      - postgres

volumes:
  nodepg_data:

networks:
  rede_node:
    driver: bridge